---
authors:
  - Sagar Paul (@KB-perByte)
dependencies:
  ansible.netcommon: ">=6.0.0"
  ansible.utils: ">=3.0.0"
license_file: LICENSE
name: acls
description:
  Ansible Network Acls enables user to manage the Acls resources independent
  of platforms and perform acls health checks.
namespace: network
readme: README.md
repository: https://github.com/redhat-cop/network.acls
issues: https://github.com/redhat-cop/network.acls/issues
tags: [networking]
version: "4.0.0"
