# fmt: off
[
  {
    "name": "name", # interface GigabitEthernet2
    "getval": '''^interface\s(?P<name>\S+)$''',
    "result": { "{{ name }}": { "name": "{{ name }}" } },
    "shared": True,
  },
  {
    "name": "inbound", # \s\sip access-group acl_1 ingress
    "getval": '''\s*ip\saccess-group\s(?P<inbound>\S+)\sin''',
    "result": { "{{ name }}": { "inbound_v4": "{{ inbound }}" } },
  },
  {
    "name": "outbound", # \s\sip access-group acl_2 out
    "getval": '''\s*ip\saccess-group\s(?P<outbound>\S+)\sout''',
    "result": { "{{ name }}": { "outbound_v4": "{{ outbound }}" } },
  },
  {
    "name": "inboundv6", # \s\sipv6 access-group acl6_1 in
    "getval": '''\s*ipv6\saccess-group\s(?P<inboundv6>\S+)\sin''',
    "result": { "{{ name }}": { "inbound_v6": "{{ inboundv6 }}" } },
  },
  {
    "name": "outboundv6", # \s\sipv6 access-group acl6_2 out
    "getval": '''\s*ipv6\saccess-group\s(?P<outboundv6>\S+)\sout''',
    "result": { "{{ name }}": { "outbound_v6": "{{ outboundv6 }}" } },
  },
]
# fmt: on
